// config.js

// Mapbox 액세스 토큰(토큰 뒤 공백 확인!!!)
const MAPBOX_ACCESS_TOKEN = 'pk.eyJ1IjoiZGVzaWduZXJhaiIsImEiOiJjaXZqNDFuMWswMjN0MnRwM3l3NjJuaXNqIn0.O5DQoymT7cb0VKaSxZN_ZQ';

// 국가 목록 데이터 (center: [경도, 위도], zoom: 초기 줌 레벨)
// tag: 특별한 내용 (예: #분쟁지역), tagColor: 태그 색상 (CSS 색상 값) 체크 필요
const COUNTRIES_DATA = [
    { "name": "대한민국", "iso": "KOR", "center": [127.7, 36], "zoom": 6 },
    { "name": "가나", "iso": "GHA", "center": [-1.2, 7.8], "zoom": 6 },
    { "name": "가봉", "iso": "GAB", "center": [11.8, 0], "zoom": 6 },
    { "name": "가이아나", "iso": "GUY", "center": [-58.9, 5], "zoom": 6, "tag": "#분쟁지역", "tagColor": "red" },
    { "name": "감비아", "iso": "GMB", "center": [-15, 13.4], "zoom": 7 },
    { "name": "건지섬", "iso": "GGY", "center": [-2.4, 49.45], "zoom": 9 },
    { "name": "과들루프", "iso": "GLP", "center": [-61.58, 16.25], "zoom": 8 }, // 추가
    { "name": "과테말라", "iso": "GTM", "center": [-90.2, 15.7], "zoom": 6 },
    { "name": "괌", "iso": "GUM", "center": [144.78, 13.47], "zoom": 8 },
    { "name": "그레나다", "iso": "GRD", "center": [-61.6, 12.1], "zoom": 9 },
    { "name": "그리스", "iso": "GRC", "center": [22, 39], "zoom": 5 },
    { "name": "그린란드", "iso": "GRL", "center": [-40, 72], "zoom": 3 }, // 추가
    { "name": "기니", "iso": "GIN", "center": [-10.8, 10], "zoom": 6 },
    { "name": "기니비사우", "iso": "GNB", "center": [-15.2, 11.8], "zoom": 7 },
    { "name": "나미비아", "iso": "NAM", "center": [17, -22], "zoom": 5 },
    { "name": "나우루", "iso": "NRU", "center": [166.9, -0.5], "zoom": 12 },
    { "name": "나이지리아", "iso": "NGA", "center": [8, 9], "zoom": 5 },
    { "name": "남극", "iso": "ATA", "center": [0, -90], "zoom": 2 },
    { "name": "남수단", "iso": "SSD", "center": [30, 7], "zoom": 5, "tag": "#분쟁지역", "tagColor": "red" },
    { "name": "남아프리카 공화국", "iso": "ZAF", "center": [24, -29], "zoom": 5 },
    { "name": "네덜란드", "iso": "NLD", "center": [5.7, 52.1], "zoom": 6 },
    { "name": "네팔", "iso": "NPL", "center": [84.1, 28.3], "zoom": 6, "tag": "#분쟁지역", "tagColor": "red" },
    { "name": "노르웨이", "iso": "NOR", "center": [8, 60], "zoom": 4 },
    { "name": "노퍽섬", "iso": "NFK", "center": [167.95, -29.03], "zoom": 8 },
    { "name": "누벨칼레도니", "iso": "NCL", "center": [165.6, -21.2], "zoom": 6 }, // 추가
    { "name": "뉴질랜드", "iso": "NZL", "center": [174.8, -41], "zoom": 5 },
    { "name": "니우에", "iso": "NIU", "center": [-169.9, -19.05], "zoom": 9 }, // 추가
    { "name": "니제르", "iso": "NER", "center": [8, 17.5], "zoom": 5 },
    { "name": "니카라과", "iso": "NIC", "center": [-85.2, 13], "zoom": 6 },
    { "name": "대만", "iso": "TWN", "center": [121, 23.7], "zoom": 7 },
    { "name": "덴마크", "iso": "DNK", "center": [9.5, 56], "zoom": 6 },
    { "name": "도미니카 공화국", "iso": "DOM", "center": [-70.1, 19], "zoom": 7 },
    { "name": "도미니카 연방", "iso": "DMA", "center": [-61.3, 15.4], "zoom": 9 },
    { "name": "독일", "iso": "DEU", "center": [10.4, 51.2], "zoom": 5 },
    { "name": "동티모르", "iso": "TLS", "center": [125.9, -8.8], "zoom": 8 },
    { "name": "라오스", "iso": "LAO", "center": [102.3, 19.8], "zoom": 6 },
    { "name": "라이베리아", "iso": "LBR", "center": [-9.4, 6.5], "zoom": 6 },
    { "name": "라트비아", "iso": "LVA", "center": [24.7, 56.8], "zoom": 7 },
    { "name": "러시아 연방", "iso": "RUS", "center": [90, 60], "zoom": 2 },
    { "name": "레바논", "iso": "LBN", "center": [35.8, 33.8], "zoom": 8 },
    { "name": "레소토", "iso": "LSO", "center": [28.2, -29.5], "zoom": 8 },
    { "name": "레위니옹", "iso": "REU", "center": [55.5, -21.1], "zoom": 8 }, // 추가
    { "name": "루마니아", "iso": "ROU", "center": [25, 46], "zoom": 6 },
    { "name": "룩셈부르크", "iso": "LUX", "center": [6.1, 49.8], "zoom": 9 },
    { "name": "르완다", "iso": "RWA", "center": [29.9, -1.9], "zoom": 8 },
    { "name": "리비아", "iso": "LBY", "center": [17, 28], "zoom": 5 },
    { "name": "리투아니아", "iso": "LTU", "center": [23.8, 55.2], "zoom": 7 },
    { "name": "리히텐슈타인", "iso": "LIE", "center": [9.5, 47.1], "zoom": 10 },
    { "name": "마다가스카르", "iso": "MDG", "center": [47, -18.9], "zoom": 5 },
    { "name": "마르티니크", "iso": "MTQ", "center": [-61, 14.6], "zoom": 8 },
    { "name": "마셜 제도", "iso": "MHL", "center": [168, 7.1], "zoom": 8 },
    { "name": "마요트", "iso": "MYT", "center": [45.1, -12.8], "zoom": 9 },
    { "name": "마카오", "iso": "MAC", "center": [113.55, 22.17], "zoom": 10 },
    { "name": "말라위", "iso": "MWI", "center": [34.3, -13.9], "zoom": 6 },
    { "name": "말레이시아", "iso": "MYS", "center": [102, 4.2], "zoom": 5 },
    { "name": "말리", "iso": "MLI", "center": [-2, 17], "zoom": 5 },
    { "name": "맨섬", "iso": "IMN", "center": [-4.5, 54.2], "zoom": 8 },
    { "name": "멕시코", "iso": "MEX", "center": [-102, 23.6], "zoom": 4 },
    { "name": "모나코", "iso": "MCO", "center": [7.4, 43.7], "zoom": 12 },
    { "name": "모로코", "iso": "MAR", "center": [-8, 32], "zoom": 5, "tag": "#분쟁지역", "tagColor": "red" },
    { "name": "모리셔스", "iso": "MUS", "center": [57.5, -20.3], "zoom": 9 },
    { "name": "모리타니", "iso": "MRT", "center": [-10, 20], "zoom": 5 },
    { "name": "모잠비크", "iso": "MOZ", "center": [35, -18.2], "zoom": 5 },
    { "name": "몬테네그로", "iso": "MNE", "center": [19.2, 42.7], "zoom": 7 },
    { "name": "몬트세랫", "iso": "MSR", "center": [-62.2, 16.7], "zoom": 9 },
    { "name": "몰도바", "iso": "MDA", "center": [28.5, 47.4], "zoom": 7 },
    { "name": "몰디브", "iso": "MDV", "center": [73.2, 3.2], "zoom": 8 },
    { "name": "몰타", "iso": "MLT", "center": [14.4, 35.9], "zoom": 10 },
    { "name": "몽골", "iso": "MNG", "center": [103.8, 46.8], "zoom": 4 },
    { "name": "미국", "iso": "USA", "center": [-95.7, 39.8], "zoom": 3 },
    { "name": "미국령 군소 제도", "iso": "UMI", "center": [170, 19], "zoom": 3 },
    { "name": "미국령 버진아일랜드", "iso": "VIR", "center": [-64.8, 18.3], "zoom": 8 },
    { "name": "미얀마", "iso": "MMR", "center": [96.1, 22], "zoom": 5 },
    { "name": "미크로네시아 연방", "iso": "FSM", "center": [150, 7], "zoom": 7 },
    { "name": "바누아투", "iso": "VUT", "center": [167, -15.4], "zoom": 7 },
    { "name": "바레인", "iso": "BHR", "center": [50.5, 26], "zoom": 9 },
    { "name": "바베이도스", "iso": "BRB", "center": [-59.5, 13.1], "zoom": 9 },
    { "name": "바티칸 시국 (성좌)", "iso": "VAT", "center": [12.45, 41.9], "zoom": 12 },
    { "name": "바하마", "iso": "BHS", "center": [-78, 25], "zoom": 7 },
    { "name": "방글라데시", "iso": "BGD", "center": [90.2, 23.7], "zoom": 7 },
    { "name": "버뮤다", "iso": "BMU", "center": [-64.75, 32.3], "zoom": 9 },
    { "name": "베냉", "iso": "BEN", "center": [2.2, 9.3], "zoom": 6 },
    { "name": "베네수엘라", "iso": "VEN", "center": [-66, 8], "zoom": 5, "tag": "#분쟁지역", "tagColor": "red" },
    { "name": "베트남", "iso": "VNM", "center": [108, 16], "zoom": 5 },
    { "name": "벨기에", "iso": "BEL", "center": [4.4, 50.5], "zoom": 7 },
    { "name": "벨라루스", "iso": "BLR", "center": [27.9, 53.7], "zoom": 6 },
    { "name": "벨리즈", "iso": "BLZ", "center": [-88.8, 17.2], "zoom": 7 },
    { "name": "보네르섬", "iso": "BES", "center": [-68.2, 12.2], "zoom": 9 }, // 추가
    { "name": "보스니아 헤르체고비나", "iso": "BIH", "center": [17.8, 44], "zoom": 7 },
    { "name": "보츠와나", "iso": "BWA", "center": [24.7, -22.3], "zoom": 5 },
    { "name": "볼리비아", "iso": "BOL", "center": [-64.6, -16.2], "zoom": 5 },
    { "name": "부룬디", "iso": "BDI", "center": [29.9, -3.4], "zoom": 8 },
    { "name": "부르키나파소", "iso": "BFA", "center": [-1.7, 12.2], "zoom": 6 },
    { "name": "부베섬", "iso": "BVT", "center": [3.4, -54.4], "zoom": 11 },
    { "name": "부탄", "iso": "BTN", "center": [90.4, 27.5], "zoom": 7, "tag": "#분쟁지역", "tagColor": "red" },
    { "name": "북마리아나 제도", "iso": "MNP", "center": [145, 15.2], "zoom": 7 },
    { "name": "북마케도니아", "iso": "MKD", "center": [21.7, 41.6], "zoom": 7 },
    { "name": "북한", "iso": "PRK", "center": [127, 40], "zoom": 6 },
    { "name": "불가리아", "iso": "BGR", "center": [25, 42.7], "zoom": 6 },
    { "name": "브라질", "iso": "BRA", "center": [-51.9, -14.2], "zoom": 3 },
    { "name": "브루나이 다루살람", "iso": "BRN", "center": [114.7, 4.5], "zoom": 8 },
    { "name": "사모아", "iso": "WSM", "center": [-172.1, -13.7], "zoom": 8 },
    { "name": "사우디아라비아", "iso": "SAU", "center": [45, 25], "zoom": 4 },
    { "name": "사우스조지아 사우스샌드위치 제도", "iso": "SGS", "center": [-37, -54.5], "zoom": 5 }, // 추가
    { "name": "산마리노", "iso": "SMR", "center": [12.4, 43.9], "zoom": 11 },
    { "name": "상투메 프린시페", "iso": "STP", "center": [6.6, 0.2], "zoom": 9 },
    { "name": "생마르탱 (프랑스령)", "iso": "MAF", "center": [-63.05, 18.07], "zoom": 9 },
    { "name": "생바르텔레미", "iso": "BLM", "center": [-62.85, 17.9], "zoom": 10 },
    { "name": "생피에르 미클롱", "iso": "SPM", "center": [-56.3, 46.8], "zoom": 8 },
    { "name": "서사하라", "iso": "ESH", "center": [-13, 24], "zoom": 5, "tag": "#분쟁지역", "tagColor": "red" },
    { "name": "세네갈", "iso": "SEN", "center": [-14.4, 14.5], "zoom": 6 },
    { "name": "세르비아", "iso": "SRB", "center": [20, 44], "zoom": 6, "tag": "#분쟁지역", "tagColor": "red" },
    { "name": "세이셸", "iso": "SYC", "center": [55.5, -4.6], "zoom": 8 },
    { "name": "세인트루시아", "iso": "LCA", "center": [-61, 13.9], "zoom": 9 },
    { "name": "세인트빈센트 그레나딘", "iso": "VCT", "center": [-61.2, 13.2], "zoom": 9 },
    { "name": "세인트키츠 네비스", "iso": "KNA", "center": [-62.7, 17.3], "zoom": 9 },
    { "name": "세인트헬레나", "iso": "SHN", "center": [-5.7, -15.95], "zoom": 8 },
    { "name": "소말리아", "iso": "SOM", "center": [46, 10], "zoom": 5, "tag": "#분쟁지역", "tagColor": "red" },
    { "name": "솔로몬 제도", "iso": "SLB", "center": [159, -8], "zoom": 6 },
    { "name": "수단", "iso": "SDN", "center": [30, 15], "zoom": 5, "tag": "#분쟁지역", "tagColor": "red" },
    { "name": "수리남", "iso": "SUR", "center": [-56, 4], "zoom": 6, "tag": "#분쟁지역", "tagColor": "red" },
    { "name": "스리랑카", "iso": "LKA", "center": [80.7, 7.8], "zoom": 7 },
    { "name": "스발바르 얀마옌 제도", "iso": "SJM", "center": [23, 78], "zoom": 4 },
    { "name": "스웨덴", "iso": "SWE", "center": [16, 62], "zoom": 4 },
    { "name": "스위스", "iso": "CHE", "center": [8.2, 46.8], "zoom": 7 },
    { "name": "스페인", "iso": "ESP", "center": [-3.7, 40.4], "zoom": 5 },
    { "name": "슬로바키아", "iso": "SVK", "center": [19.7, 48.7], "zoom": 7 },
    { "name": "슬로베니아", "iso": "SVN", "center": [14.9, 46.1], "zoom": 7 },
    { "name": "시리아", "iso": "SYR", "center": [38, 35], "zoom": 5, "tag": "#분쟁지역", "tagColor": "red" },
    { "name": "시에라리온", "iso": "SLE", "center": [-11.8, 8.5], "zoom": 6 },
    { "name": "신트마르턴(네덜란드령)", "iso": "SXM", "center": [-63.05, 18.03], "zoom": 9 },
    { "name": "싱가포르", "iso": "SGP", "center": [103.8, 1.3], "zoom": 10 },
    { "name": "아랍에미리트", "iso": "ARE", "center": [54, 24], "zoom": 6 },
    { "name": "아루바", "iso": "ABW", "center": [-70, 12.5], "zoom": 9 },
    { "name": "아르메니아", "iso": "ARM", "center": [45, 40], "zoom": 7 },
    { "name": "아르헨티나", "iso": "ARG", "center": [-64, -34], "zoom": 3 },
    { "name": "아메리칸사모아", "iso": "ASM", "center": [-170, -14.3], "zoom": 8 },
    { "name": "아이슬란드", "iso": "ISL", "center": [-19, 64.9], "zoom": 5 },
    { "name": "아이티", "iso": "HTI", "center": [-72.5, 19], "zoom": 7 },
    { "name": "아일랜드", "iso": "IRL", "center": [-7, 53.4], "zoom": 6 },
    { "name": "아제르바이잔", "iso": "AZE", "center": [47.5, 40], "zoom": 6 },
    { "name": "아프가니스탄", "iso": "AFG", "center": [66, 33], "zoom": 5, "tag": "#분쟁지역", "tagColor": "red" },
    { "name": "안도라", "iso": "AND", "center": [1.6, 42.5], "zoom": 10 },
    { "name": "알바니아", "iso": "ALB", "center": [20, 41], "zoom": 7 },
    { "name": "알제리", "iso": "DZA", "center": [3, 28], "zoom": 4 },
    { "name": "앙골라", "iso": "AGO", "center": [17.5, -12.5], "zoom": 5 },
    { "name": "앵귈라", "iso": "AIA", "center": [-63.05, 18.22], "zoom": 9 },
    { "name": "앤티가 바부다", "iso": "ATG", "center": [-61.8, 17], "zoom": 9 },
    { "name": "에리트레아", "iso": "ERI", "center": [39, 15], "zoom": 6 },
    { "name": "에스와티니", "iso": "SWZ", "center": [31.5, -26.5], "zoom": 8 },
    { "name": "에스토니아", "iso": "EST", "center": [25, 58.7], "zoom": 7 },
    { "name": "에콰도르", "iso": "ECU", "center": [-78.2, -1.8], "zoom": 6 },
    { "name": "에티오피아", "iso": "ETH", "center": [39.6, 9.1], "zoom": 5, "tag": "#분쟁지역", "tagColor": "red" },
    { "name": "엘살바도르", "iso": "SLV", "center": [-88.9, 13.8], "zoom": 7 },
    { "name": "영국", "iso": "GBR", "center": [-2, 54], "zoom": 5 },
    { "name": "영국령 버진아일랜드", "iso": "VGB", "center": [-64.6, 18.4], "zoom": 8 },
    { "name": "영국령 인도양 지역", "iso": "IOT", "center": [71.5, -6], "zoom": 6 },
    { "name": "예멘", "iso": "YEM", "center": [47.5, 15.5], "zoom": 5, "tag": "#분쟁지역", "tagColor": "red" },
    { "name": "오만", "iso": "OMN", "center": [57, 21], "zoom": 5 },
    { "name": "오스트레일리아", "iso": "AUS", "center": [133, -25], "zoom": 3 },
    { "name": "오스트리아", "iso": "AUT", "center": [14.6, 47.6], "zoom": 6 },
    { "name": "온두라스", "iso": "HND", "center": [-86.2, 15.2], "zoom": 6 },
    { "name": "올란드 제도", "iso": "ALA", "center": [20, 60.1], "zoom": 8 }, // 추가
    { "name": "왈리스 푸투나", "iso": "WLF", "center": [-176.2, -13.7], "zoom": 8 }, // 추가
    { "name": "요르단", "iso": "JOR", "center": [36.7, 31], "zoom": 6 },
    { "name": "우간다", "iso": "UGA", "center": [32, 1], "zoom": 6 },
    { "name": "우루과이", "iso": "URY", "center": [-56, -33], "zoom": 6 },
    { "name": "우즈베키스탄", "iso": "UZB", "center": [63, 41], "zoom": 5 },
    { "name": "우크라이나", "iso": "UKR", "center": [32, 49], "zoom": 5, "tag": "#분쟁지역", "tagColor": "red" },
    { "name": "이라크", "iso": "IRQ", "center": [44, 33], "zoom": 5 },
    { "name": "이란", "iso": "IRN", "center": [53, 32], "zoom": 5 },
    { "name": "이스라엘", "iso": "ISR", "center": [34.8, 31.5], "zoom": 7, "tag": "#분쟁지역", "tagColor": "red" },
    { "name": "이집트", "iso": "EGY", "center": [29.9, 26], "zoom": 5, "tag": "#분쟁지역", "tagColor": "red" },
    { "name": "이탈리아", "iso": "ITA", "center": [12.5, 42], "zoom": 5 },
    { "name": "인도", "iso": "IND", "center": [78, 22], "zoom": 4, "tag": "#분쟁지역", "tagColor": "red" },
    { "name": "인도네시아", "iso": "IDN", "center": [118, -2.5], "zoom": 4 },
    { "name": "일본", "iso": "JPN", "center": [138, 36], "zoom": 5 },
    { "name": "자메이카", "iso": "JAM", "center": [-77.5, 18.2], "zoom": 7 },
    { "name": "잠비아", "iso": "ZMB", "center": [28, -13], "zoom": 5 },
    { "name": "적도 기니", "iso": "GNQ", "center": [10, 1.6], "zoom": 7 },
    { "name": "저지섬", "iso": "JEY", "center": [2.1, 49.2], "zoom": 9 },
    { "name": "조지아", "iso": "GEO", "center": [43.5, 42], "zoom": 7, "tag": "#분쟁지역", "tagColor": "red" },
    { "name": "중앙아프리카 공화국", "iso": "CAF", "center": [20, 7], "zoom": 6 },
    { "name": "중국", "iso": "CHN", "center": [104.2, 35.8], "zoom": 4, "tag": "#분쟁지역", "tagColor": "red" },
    { "name": "지부티", "iso": "DJI", "center": [42.6, 11.8], "zoom": 8 },
    { "name": "지브롤터", "iso": "GIB", "center": [-5.35, 36.13], "zoom": 10, "tag": "#분쟁지역", "tagColor": "red" },
    { "name": "짐바브웨", "iso": "ZWE", "center": [29, -19], "zoom": 6 },
    { "name": "차드", "iso": "TCD", "center": [19, 15], "zoom": 5 },
    { "name": "체코", "iso": "CZE", "center": [15, 49.8], "zoom": 6 },
    { "name": "칠레", "iso": "CHL", "center": [-71, -30], "zoom": 3 },
    { "name": "카메룬", "iso": "CMR", "center": [12, 6], "zoom": 6 },
    { "name": "카보베르데", "iso": "CPV", "center": [-24, 16], "zoom": 7 },
    { "name": "카자흐스탄", "iso": "KAZ", "center": [68, 48], "zoom": 4 },
    { "name": "카타르", "iso": "QAT", "center": [51.2, 25.3], "zoom": 9 },
    { "name": "캄보디아", "iso": "KHM", "center": [104.9, 12.5], "zoom": 7 },
    { "name": "캐나다", "iso": "CAN", "center": [-105, 60], "zoom": 3 },
    { "name": "케냐", "iso": "KEN", "center": [37.9, 1], "zoom": 5, "tag": "#분쟁지역", "tagColor": "red" },
    { "name": "케이맨 제도", "iso": "CYM", "center": [-80.5, 19.3], "zoom": 8 }, // 추가
    { "name": "코모로", "iso": "COM", "center": [43.3, -11.6], "zoom": 9 },
    { "name": "코스타리카", "iso": "CRI", "center": [-84, 10], "zoom": 7 },
    { "name": "코코스 (킬링) 제도", "iso": "CCK", "center": [96.8, -12.1], "zoom": 8 },
    { "name": "코트디부아르", "iso": "CIV", "center": [-5, 8], "zoom": 6 },
    { "name": "콜롬비아", "iso": "COL", "center": [-74, 4], "zoom": 5 },
    { "name": "콩고 공화국", "iso": "COG", "center": [15, -1], "zoom": 6 },
    { "name": "콩고 민주 공화국", "iso": "COD", "center": [23, 0], "zoom": 4 },
    { "name": "쿠바", "iso": "CUB", "center": [-79, 21.5], "zoom": 6 },
    { "name": "쿠웨이트", "iso": "KWT", "center": [47.7, 29.3], "zoom": 8 },
    { "name": "쿡 제도", "iso": "COK", "center": [-159.7, -21.2], "zoom": 7 },
    { "name": "퀴라소", "iso": "CUW", "center": [-69, 12.1], "zoom": 9 },
    { "name": "크로아티아", "iso": "HRV", "center": [15.5, 45.1], "zoom": 6 },
    { "name": "크리스마스섬", "iso": "CXR", "center": [105.6, -10.4], "zoom": 8 },
    { "name": "키르기스스탄", "iso": "KGZ", "center": [74.8, 41.2], "zoom": 6 },
    { "name": "키리바시", "iso": "KIR", "center": [173, 0], "zoom": 6 },
    { "name": "키프로스", "iso": "CYP", "center": [33, 35], "zoom": 8, "tag": "#분쟁지역", "tagColor": "red" },
    { "name": "타지키스탄", "iso": "TJK", "center": [71, 39], "zoom": 6 },
    { "name": "탄자니아", "iso": "TZA", "center": [35, -6], "zoom": 5 },
    { "name": "태국", "iso": "THA", "center": [101, 15], "zoom": 5 },
    { "name": "터크스 케이커스 제도", "iso": "TCA", "center": [-71.8, 21.7], "zoom": 8 },
    { "name": "토고", "iso": "TGO", "center": [1, 8.5], "zoom": 7 },
    { "name": "토켈라우", "iso": "TKL", "center": [-172, -9], "zoom": 8 },
    { "name": "통가", "iso": "TON", "center": [-174.8, -20], "zoom": 8 },
    { "name": "투르크메니스탄", "iso": "TKM", "center": [60, 40], "zoom": 5 },
    { "name": "투발루", "iso": "TUV", "center": [178, -8], "zoom": 10 },
    { "name": "튀니지", "iso": "TUN", "center": [9, 34], "zoom": 6 },
    { "name": "튀르키예", "iso": "TUR", "center": [35, 39], "zoom": 5 },
    { "name": "트리니다드 토바고", "iso": "TTO", "center": [-61.2, 10.5], "zoom": 7 }, // 추가
    { "name": "파나마", "iso": "PAN", "center": [-80, 8.5], "zoom": 6 },
    { "name": "파라과이", "iso": "PRY", "center": [-58, -23], "zoom": 6 },
    { "name": "파키스탄", "iso": "PAK", "center": [70, 30], "zoom": 5, "tag": "#분쟁지역", "tagColor": "red" },
    { "name": "파푸아뉴기니", "iso": "PNG", "center": [145, -6], "zoom": 5 },
    { "name": "팔라우", "iso": "PLW", "center": [134.5, 7.5], "zoom": 9 },
    { "name": "팔레스타인", "iso": "PSE", "center": [35.2, 31.9], "zoom": 8, "tag": "#분쟁지역", "tagColor": "red" },
    { "name": "페로 제도", "iso": "FRO", "center": [-6.9, 62], "zoom": 7 },
    { "name": "페루", "iso": "PER", "center": [-75, -10], "zoom": 4 },
    { "name": "포클랜드 제도", "iso": "FLK", "center": [-59.5, -51.7], "zoom": 7 }, // 추가
    { "name": "포르투갈", "iso": "PRT", "center": [-8, 39.5], "zoom": 6 },
    { "name": "폴란드", "iso": "POL", "center": [19, 52], "zoom": 6 },
    { "name": "푸에르토리코", "iso": "PRI", "center": [-66.5, 18.2], "zoom": 8 },
    { "name": "프랑스", "iso": "FRA", "center": [2, 47], "zoom": 5 },
    { "name": "프랑스령 기아나", "iso": "GUF", "center": [-53.2, 4], "zoom": 6, "tag": "#국경이견", "tagColor": "red" }, // 추가
    { "name": "프랑스령 남방 및 남극 지역", "iso": "ATF", "center": [67, -49], "zoom": 4 }, // 추가
    { "name": "프랑스령 폴리네시아", "iso": "PYF", "center": [-145, -17.6], "zoom": 5 }, // 추가
    { "name": "피지", "iso": "FJI", "center": [178, -17.8], "zoom": 7 },
    { "name": "핀란드", "iso": "FIN", "center": [26, 64], "zoom": 4 },
    { "name": "필리핀", "iso": "PHL", "center": [122, 13], "zoom": 5 },
    { "name": "핏케언 제도", "iso": "PCN", "center": [-130.1, -25.07], "zoom": 8 }, // 추가
    { "name": "헝가리", "iso": "HUN", "center": [19.5, 47], "zoom": 7 },
    { "name": "허드 맥도널드 제도", "iso": "HMD", "center": [73.5, -53], "zoom": 5 },
    { "name": "홍콩", "iso": "HKG", "center": [114.1, 22.3], "zoom": 9 }
];

// 대한민국 시도 목록 데이터
const PROVINCES_DATA = [
    { "name": "서울특별시", "code": "11", "center": [126.978, 37.566], "zoom": 9 },
    { "name": "부산광역시", "code": "26", "center": [129.075, 35.179], "zoom": 9 },
    { "name": "대구광역시", "code": "27", "center": [128.601, 35.872], "zoom": 9 },
    { "name": "인천광역시", "code": "28", "center": [126.705, 37.456], "zoom": 9 },
    { "name": "광주광역시", "code": "29", "center": [126.853, 35.160], "zoom": 9 },
    { "name": "대전광역시", "code": "30", "center": [127.385, 36.351], "zoom": 9 },
    { "name": "울산광역시", "code": "31", "center": [129.311, 35.538], "zoom": 9 },
    { "name": "세종특별자치시", "code": "36", "center": [127.289, 36.480], "zoom": 10 },
    { "name": "경기도", "code": "41", "center": [127.239, 37.414], "zoom": 8 },
    { "name": "강원특별자치도", "code": "51", "center": [128.217, 37.828], "zoom": 8 },
    { "name": "충청북도", "code": "43", "center": [127.929, 36.836], "zoom": 8 },
    { "name": "충청남도", "code": "44", "center": [126.800, 36.518], "zoom": 8 },
    { "name": "전라북도", "code": "45", "center": [127.109, 35.817], "zoom": 8 },
    { "name": "전라남도", "code": "46", "center": [126.900, 34.868], "zoom": 8 },
    { "name": "경상북도", "code": "47", "center": [128.668, 36.492], "zoom": 8 },
    { "name": "경상남도", "code": "48", "center": [128.218, 35.259], "zoom": 8 },
    { "name": "제주특별자치도", "code": "50", "center": [126.531, 33.499], "zoom": 9 }
];
